name: Build and Test

on:
  workflow_call:
    inputs:
      solution-file:
        description: The name of the solution file.
        type: string
        default: example-nuget-native-static.sln
      project-name:
        description: The name of the project.  This should match the NuGet package ID.
        type: string
        default: silnith.tessellation.static

jobs:
  get-date:
    name: Date
    uses: silnith/github-workflows/.github/workflows/bash-get-date.yaml@main
  nuget-cache:
    name: NuGet Cache
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
    uses: silnith/github-workflows/.github/workflows/nuget-cache-dependencies.yaml@main
    with:
      solution-file: ${{ inputs.solution-file }}
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  msbuild-intel:
    name: C++ Intel
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - nuget-cache
    strategy:
      matrix:
        platform:
          - x86
          - x64
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/msbuild-intel.yaml@main
    with:
      solution-file: ${{ inputs.solution-file }}
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  msbuild-arm:
    name: C++ ARM
    permissions:
      contents: read
      packages: read
    needs:
      - get-date
      - nuget-cache
    strategy:
      matrix:
        platform:
          - ARM
          - ARM64
        configuration:
          - Debug
          - Release
    uses: silnith/github-workflows/.github/workflows/msbuild-arm.yaml@main
    with:
      solution-file: ${{ inputs.solution-file }}
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      year: ${{ needs.get-date.outputs.year }}
      month: ${{ needs.get-date.outputs.month }}
      day: ${{ needs.get-date.outputs.day }}
    secrets: inherit
  nuget-pack:
    name: NuGet Pack
    permissions:
      contents: read
    needs:
      - msbuild-intel
      - msbuild-arm
    uses: silnith/github-workflows/.github/workflows/nuget-package.yaml@main
    with:
      base-path: ${{ inputs.project-name }}
      nuspec-file: ${{ inputs.project-name }}.nuspec
    secrets: inherit
  vstest-results:
    name: Publish VSTest Results
    permissions:
      checks: write
    needs:
      - msbuild-intel
      - msbuild-arm
    uses: silnith/github-workflows/.github/workflows/publish-test-results.yaml@main
    with:
      check-name: C++ Test Results
      artifact-pattern: msbuild-vstest-test-results-*
      test-result-files: "**/TestResults/**/*.trx"
    secrets: inherit
