name: Push Branch

on:
  push:
    branches:
      - '*'

jobs:
  call-build:
    name: Build
    permissions:
      contents: read
      packages: read
      checks: write
    uses: ./.github/workflows/build.yaml
    secrets: inherit
