name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  call-build:
    name: Standard Build
    uses: ./.github/workflows/build.yaml
    with:
      solution_file: example-nuget-native-static.sln
      project_name: silnith.tessellation.static
    secrets: inherit
